project:
  type: website
  output-dir: docs

website:
  title: " Angus Greaves"
  twitter-card: true # some info is included when site is in a tweet (can customise)
  favicon: logo_black.png # logo for browser tabs 
  image: "logo_navbar.png"
  open-graph: true
  navbar:
    logo: "logo_navbar.png"
    pinned: true
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - text: Guides
        menu:
          - text: R for Predocs (& PhDs)
          - text: Graduate Econmetrics
          - text: Machine Learning for Economists
    right:
    - icon: twitter
      href: https://twitter.com/angus_greaves
      target: _blank
    - text: "{{< fa brands bluesky  size = lg >}}"
      href: https://bsky.app/profile/angusgreaves.bsky.social
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/angus-greaves/
      target: _blank
    - icon: file-earmark-person-fill
      href: https://angusgreaves.github.io/CV_AGreaves.pdf
      target: _blank
    - icon: google
      href: https://scholar.google.co.uk/ # edit to my google scholar page
      target: _blank        
    - icon: github
      href: https://github.com/AngusGreaves
      target: _blank
  
  page-footer: 
    left: |
      {{< fa regular copyright >}} 2025, Angus Greaves   
      Contact: angus.greaves[address sign]economics.ox.ac.uk
    right: 
      - href: https://github.com/AngusGreaves/angusgreaves.github.io 
        text: 'Report a bug' # add a link here to relevent github files
    background: floralwhite

format:
  html:
    html-head: |
      <meta name="viewport" content="width=1024">
    theme:
      - sandstone
      - brand
    backgroundcolor: floralwhite
    css: styles.css
    toc: false

editor: source